import Head from "next/head";

const CustomHeader = (props: { title: string }) => {
  return (
    <Head>
      <title>{props.title}</title>
      <meta name="description" content="Generated by the stream stats app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default CustomHeader;
